//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    static class MY_DB
    {
        public static string ConnectionString()
        {
            SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder();

            // Set the properties for the data source.
            sqlBuilder.DataSource = "contactspocdb.database.windows.net,1433";
            sqlBuilder.InitialCatalog = "ContactsDB";
            sqlBuilder.UserID = "sqladmin";
            sqlBuilder.Password = "Demo@Pass123";
            sqlBuilder.IntegratedSecurity = false;

            // Build the SqlConnection connection string.
            string providerString = sqlBuilder.ToString();

            // Initialize the EntityConnectionStringBuilder.
            EntityConnectionStringBuilder entityBuilder = new EntityConnectionStringBuilder();

            //Set the provider name.
            entityBuilder.Provider = "System.Data.SqlClient";

            // Set the provider-specific connection string.
            entityBuilder.ProviderConnectionString = providerString;

            // Set the Metadata location.
            entityBuilder.Metadata = @"res://*/ContactsModel.csdl|
				       res://*/ContactsModel.ssdl|
				       res://*/ContactsModel.msl";
            return entityBuilder.ToString();

        }
    }
    public partial class ContactsDBEntities : DbContext
    {
        public ContactsDBEntities()
            : base(MY_DB.ConnectionString())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactImage> ContactImages { get; set; }
    }
}
